version: 0.0
os: linux
files:
  - source: /**
    destination: /home/ec2-user/build/
    overwirte: yes
hooks:
  BeforeInstall:
    - location: deploy-before.sh
      timeout: 100
      runas: root
  # AfterInstall:
  #   - location: scripts/change_permissions.sh
  #     timeout: 300
  #     runas: root
  ApplicationStart:
    - location: deploy.sh
      timeout: 100
      runas: root
  # ApplicationStop:
  #   - location: scripts/stop_server.sh
  #     timeout: 300
  #     runas: root