version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/build
    overwirte: yes
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 100
      runas: ec2-user
  # ApplicationStop:
  #   - location: scripts/stop_server.sh
  #     timeout: 300
  #     runas: root